coffee_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('users/', include('users.urls')),
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .views import MyOrderView, CreateOrderProductView

urlpatterns = [
    path('my_order', MyOrderView.as_view(), name='my_order'),
    path('add-product', CreateOrderProductView.as_view(), name='add_product')
]

products/urls.py
from django.urls import path
from .views import ProductFormView, ProductListView, ProductListAPI

urlpatterns = [
    path('', ProductListView.as_view(), name='list_product'),
    path('api/', ProductListAPI.as_view(), name='list_product_api'),
    path('add/', ProductFormView.as_view(), name='add_product'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .views import RegisterView

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
]

orders/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product


# Create your models here.
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    order_date = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'order {self.id} by {self.user}'


class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity = models.IntegerField()

    def __str__(self) -> str:
        return f'{self.order} - {self.product}'

products/models.py
from django.db import models


# Create your models here.
class Product(models.Model):
    name = models.TextField(max_length=200, verbose_name='nombre')
    description = models.TextField(max_length=300, verbose_name='descripción')
    price = models.DecimalField(
        max_digits=10, decimal_places=2, verbose_name='precio')
    available = models.BooleanField(default=True, verbose_name='disponible')
    photo = models.ImageField(
        upload_to='logos', null=True, blank=True, verbose_name='foto')

    def __str__(self):
        return self.name

orders/forms.py
from django.forms import ModelForm
from .models import OrderProduct


class OrderProductForm(ModelForm):
    class Meta:
        model = OrderProduct
        fields = ['product']

products/forms.py
from django import forms
from .models import Product


class ProductForm(forms.Form):
    name = forms.CharField(max_length=200, label='Nombre')
    description = forms.CharField(max_length=300, label='Descripción')
    price = forms.DecimalField(max_digits=10, decimal_places=2, label='Precio')
    available = forms.BooleanField(
        initial=True, label='Disponible', required=False)
    photo = forms.ImageField(label='Foto', required=False)

    def save(self):
        Product.objects.create(
            name=self.cleaned_data['name'],
            description=self.cleaned_data['description'],
            price=self.cleaned_data['price'],
            available=self.cleaned_data['available'],
            photo=self.cleaned_data['photo'],
        )

orders/views.py
from django.views.generic import DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import Order
from .forms import OrderProductForm


# Create your views here.
class MyOrderView(LoginRequiredMixin, DetailView):
    model = Order
    template_name = 'orders/my_order.html'
    context_object_name = 'order'

    def get_object(self, queryset=None):
        return Order.objects.filter(is_active=True, user=self.request.user).first()


class CreateOrderProductView(LoginRequiredMixin, CreateView):
    template_name = 'orders/create_order_product.html'
    form_class = OrderProductForm
    success_url = reverse_lazy('my_order')

    def form_valid(self, form):
        order, _ = Order.objects.get_or_create(
            is_active=True,
            user=self.request.user
        )
        form.instance.order = order
        form.instance.quantity = 1
        form.save()
        return super().form_valid(form)

products/views.py
from django.views import generic
from django.urls import reverse_lazy
from rest_framework.views import APIView
from rest_framework.response import Response

from products.models import Product
from .forms import ProductForm
from .serializers import ProductSerializer


# Create your views here.
class ProductFormView(generic.FormView):
    template_name = 'products/add_product.html'
    form_class = ProductForm
    success_url = reverse_lazy('add_product')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class ProductListView(generic.ListView):
    model = Product
    template_name = 'products/list_product.html'
    context_object_name = 'products'


class ProductListAPI(APIView):
    authentication_classes = []
    permission_classes = []

    def get(self, request):
        products = Product.objects.all()
        serializer = ProductSerializer(products, many=True)
        return Response(serializer.data)

users/views.py
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.urls import reverse_lazy


# Create your views here.
class RegisterView(generic.CreateView):
    form_class = UserCreationForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('login')

orders/templates/orders/my_order.html
{% extends "base.html" %} {% block content %}

<div class="max-w-4xl mx-auto p-6 bg-white rounded-lg shadow-md mt-6">
  <h2 class="text-2xl font-bold mb-4">Detalles de la orden</h2>
  <div class="mb-2">
    <span class="text-lg font-semibold">Usuario: </span>
    <span class="text-lg">{{ order.user.username|title }}</span>
  </div>
  <div class="mb-2">
    <span class="text-lg font-semibold">Fecha de la orden: </span>
    <span class="text-lg">{{ order.order_date|date:"F j, Y H:m" }}</span>
  </div>

  <div class="mt-6">
    <h3 class="text-xl font-bold mb-2">Artículos en tu orden:</h3>
    {% for product_order in order.orderproduct_set.all %}
    <div class="flex justify-between items-center py-2 border-b">
      <div class="text-lg">{{ product_order.product.name }}</div>
      <div class="text-lg font-semibold">{{ product_order.product.price}}</div>
    </div>
    {% empty %}
    <div class="text-red-500">No hay artículos en tu orden</div>
    {% endfor %}
  </div>
</div>
{% endblock content %}

products/templates/products/add_product.html
<h1>Agregar nuevos productos</h1>
<form action="{% url 'add_product' %}" method="post">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">Agregar</button>
</form>

products/templates/products/list_product.html
{% extends "base.html" %} {% block content %}
<h1 class="text-3xl font-bold my-8 text-center">Lista de productos</h1>

<div class="grid grid-cols-1 gap-4 md:grid-cols-2 md:gap-8 mt-8">
  {% for product in products %}
  <a href="#" class="group relative block overflow-hidden">
    <button
      class="absolute end-4 top-4 z-10 rounded-full bg-white p-1.5 text-gray-900 transition hover:text-gray-900/75"
    >
      <span class="sr-only">Wishlist</span>

      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        stroke-width="1.5"
        stroke="currentColor"
        class="h-4 w-4"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z"
        />
      </svg>
    </button>

    {% if product.photo %}
    <img
      src="{{ product.photo.url }}"
      alt="{{ product.name }}"
      class="h-64 w-full object-cover transition duration-500 group-hover:scale-105 sm:h-72"
    />
    {% endif %}

    <div class="relative border border-gray-100 bg-white p-6">
      <span class="whitespace-nowrap bg-yellow-400 px-3 py-1.5 text-xs font-medium"> New </span>

      <h3 class="mt-4 text-lg font-medium text-gray-900">{{ product.name }}</h3>

      <p class="mt-1.5 text-sm text-gray-700">${{ product.price }}</p>

      <form action="{% url 'add_product' %}" method="post" class="mt-4">
        {% csrf_token %}
        <input type="hidden" name="product" value="{{ product.id }}" />
        <button
          class="block w-full rounded bg-yellow-400 p-4 text-sm font-medium transition hover:scale-105"
        >
          Añadir al carrito
        </button>
      </form>
    </div>
  </a>
  {% endfor %}
</div>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Coffee Shop</title>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    <header>
      <nav
        class="bg-white border-gray-200 px-4 lg:px-6 py-2.5 dark:bg-gray-800">
        <div
          class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl">
          <a href="{% url "list_product" %}" class="flex items-center">
            <svg
              class="size-10"
              xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 300"
              xml:space="preserve"><path fill="#F4F4F4"
                d="m82.85 62.995 17.814 24.543 11.666 83.799h65.006l15.118-108.342z" /><path
                fill="#AA6148" d="M112.33 171.337h65.006v19.653H112.33z" /><path
                fill="#F4F4F4"
                d="M192.454 255.164H97.212l15.118-64.174h65.006z" /><path
                fill="#EFEFEF"
                d="m173.68 62.995-15.118 108.342h18.774l15.118-108.342zM177.336 190.99h-18.774l15.118 64.174h18.774z" /><path
                fill="#F9F9F9"
                d="M101.476 62.995H82.85l17.814 24.543 11.666 83.799h18.626l-11.667-83.799zM112.33 190.99l-15.118 64.174h18.626l15.118-64.174z" /><path
                fill="#AA6148"
                d="M97.212 255.164h95.242v15.78H97.212zM192.454 62.995c0-9.655-6.177-16.128-17.82-16.128h-59.601c-11.644 0-17.821 8.064-17.821 16.128h95.242zM150.675 46.867l1.709-10.258a7.555 7.555 0 0 0-7.553-7.553 7.555 7.555 0 0 0-7.552 7.553l1.71 10.258h11.686z" /><path
                fill="#BC715C"
                d="M122.585 46.867h-7.552c-11.644 0-17.821 8.064-17.821 16.128h7.551c0-8.064 6.178-16.128 17.822-16.128zM148.609 30.104c-1.115-.649-2.393-1.048-3.776-1.048a7.555 7.555 0 0 0-7.552 7.553l1.71 10.258h7.552l-1.709-10.258c-.002-2.787 1.526-5.196 3.775-6.505z" /><path
                fill="#AA6148"
                d="m192.454 62.995-1.955 14.028h12.667v74.772a6.991 6.991 0 0 0 6.992 6.992 6.991 6.991 0 0 0 6.992-6.992v-88.8h-24.696z" /><path
                fill="#BC715C"
                d="m192.454 62.995-1.955 14.028h6.549l1.958-14.028zM209.715 151.795V77.023h-6.549v74.772a6.991 6.991 0 0 0 6.992 6.992c1.187 0 2.291-.325 3.272-.85-2.2-1.175-3.715-3.47-3.715-6.142zM112.33 171.337h18.626v19.653H112.33z" /><path
                fill="#964636"
                d="M158.562 171.337h18.774v19.653h-18.774z" /><g><path
                  fill="#BC715C"
                  d="M97.59 255.164h18.626v15.78H97.59z" /></g><g><path
                  fill="#161616"
                  d="M177.336 175.872H112.33a4.537 4.537 0 0 1-4.493-3.909l-6.958-49.984a4.535 4.535 0 0 1 3.867-5.117 4.534 4.534 0 0 1 5.119 3.865l6.413 46.074h57.11l13.854-99.271H91.746l12.588 17.344c.437.602.719 1.302.822 2.037l1.795 12.892a4.535 4.535 0 0 1-3.867 5.117 4.531 4.531 0 0 1-5.119-3.865l-1.639-11.77L79.18 65.658a4.537 4.537 0 0 1-.371-4.724 4.537 4.537 0 0 1 4.041-2.474h109.604a4.533 4.533 0 0 1 4.491 5.161l-15.118 108.341a4.536 4.536 0 0 1-4.491 3.91z" /><path
                  fill="#161616"
                  d="M177.336 195.525H112.33a4.536 4.536 0 0 1-4.535-4.535v-19.653a4.535 4.535 0 0 1 4.535-4.535h65.006a4.536 4.536 0 0 1 4.535 4.535v19.653a4.536 4.536 0 0 1-4.535 4.535zm-60.471-9.071H172.8v-10.583h-55.935v10.583z" /><path
                  fill="#161616"
                  d="M192.454 259.7H97.212a4.534 4.534 0 0 1-4.414-5.574l15.118-64.175a4.536 4.536 0 0 1 4.414-3.496h65.006a4.532 4.532 0 0 1 4.414 3.496l15.118 64.175a4.539 4.539 0 0 1-4.414 5.574zm-89.514-9.071h83.785l-12.98-55.104H115.92l-12.98 55.104z" /><path
                  fill="#161616"
                  d="M192.454 275.479h-15.118a4.536 4.536 0 0 1 0-9.07h10.583V259.7h-86.171v6.709h54.665a4.536 4.536 0 0 1 0 9.07H97.212a4.535 4.535 0 0 1-4.535-4.535v-15.779a4.535 4.535 0 0 1 4.535-4.535h95.242a4.536 4.536 0 0 1 4.535 4.535v15.779a4.536 4.536 0 0 1-4.535 4.535zM192.454 67.53H97.212a4.536 4.536 0 0 1-4.535-4.535c0-10.016 7.835-20.663 22.357-20.663h59.601c13.58 0 22.355 8.111 22.355 20.663a4.538 4.538 0 0 1-4.536 4.535zm-89.762-9.07h84.55c-1.931-5.713-7.656-7.057-12.608-7.057h-59.601c-6.638 0-10.646 3.177-12.341 7.057z" /><path
                  fill="#161616"
                  d="M150.675 51.403H138.99a4.535 4.535 0 0 1-4.473-3.788l-1.71-10.258a4.564 4.564 0 0 1-.062-.747c0-6.664 5.423-12.089 12.087-12.089 6.666 0 12.089 5.424 12.089 12.089 0 .251-.021.499-.062.747l-1.71 10.258a4.535 4.535 0 0 1-4.474 3.788zm-7.843-9.071h4.002l1.002-6.015a3.023 3.023 0 0 0-3.004-2.725 3.023 3.023 0 0 0-3.003 2.725l1.003 6.015zM210.158 163.323c-6.357 0-11.528-5.17-11.528-11.527V81.559h-8.132a4.533 4.533 0 0 1-4.491-5.161l1.955-14.028a4.533 4.533 0 0 1 4.491-3.909h24.697a4.536 4.536 0 0 1 4.535 4.535v88.8c.001 6.356-5.17 11.527-11.527 11.527zM195.71 72.488h7.456a4.536 4.536 0 0 1 4.535 4.535v74.772a2.458 2.458 0 0 0 4.914 0V67.53h-16.213l-.692 4.958z" /></g>
            </svg>
            <span
              class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">Coffee
              Shop</span>
          </a>
          <div class="flex items-center lg:order-2">
            {% if user.is_authenticated %}
            <form action="{% url "logout" %}" method="post">
              {% csrf_token %}
              <button type="submit"
                class="text-gray-800 dark:text-white hover:bg-gray-50 focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-4 lg:px-5 py-2 lg:py-2.5 mr-2 dark:hover:bg-gray-700 focus:outline-none dark:focus:ring-gray-800">
                Cerrar sesión
              </button>
            </form>
            {% else %}
            <a href="{% url "login" %}"
              class="text-gray-800 dark:text-white hover:bg-gray-50 focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-4 lg:px-5 py-2 lg:py-2.5 mr-2 dark:hover:bg-gray-700 focus:outline-none dark:focus:ring-gray-800">
              Login
            </a>
            {% endif %}
            <a href="{% url 'my_order' %}"
              class="text-white bg-indigo-700 hover:bg-indigo-800 focus:ring-4 focus:ring-indigo-300 font-medium rounded-lg text-sm px-4 lg:px-5 py-2 lg:py-2.5 mr-2 dark:bg-indigo-600 dark:hover:bg-indigo-700 focus:outline-none dark:focus:ring-indigo-800">
              Mi Pedido
            </a>
          </div>
        </div>
      </nav>
    </header>
    <div class="container mx-auto px-4">
      {% block content %}{% endblock content %}
    </div>

  </body>
</html>

users/templates/users/login.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}
<div class="mx-auto max-w-screen-xl px-4 py-16 sm:px-6 lg:px-8">
    <div class="mx-auto max-w-lg">
        <h1 class="text-center text-2xl font-bold text-indigo-600 sm:text-3xl">
            Inicio de sesión
        </h1>
        <p class="mx-auto mt-4 max-w-md text-center text-gray-500">
            Para poder adquirir nuestros productos y acceder a toda nuestra web
            debes iniciar sesión
        </p>
        <form action="#" method="post"
            class="mb-0 mt-6 space-y-4 rounded-lg p-4 shadow-lg sm:p-6 lg:p-8">
            <div class="relative">
                {% csrf_token %}
                {{ form|crispy }}
            </div>
            <button type="submit"
                class="block w-full rounded-lg bg-indigo-600 px-5 py-3 text-sm font-medium text-white">
                Acceder
            </button>
            <p class="text-center text-sm text-gray-500">
                No tienes una cuenta?
                <a class="underline" href="{% url 'register' %}">Regístrate</a>
            </p>
        </form>
    </div>
</div>
{% endblock content %}

users/templates/users/register.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}
<div class="mx-auto max-w-screen-xl px-4 py-16 sm:px-6 lg:px-8">
    <div class="mx-auto max-w-lg">
        <h1 class="text-center text-2xl font-bold text-indigo-600 sm:text-3xl">
            Crea tu cuenta
        </h1>
        <p class="mx-auto mt-4 max-w-md text-center text-gray-500">
            Crea tu cuenta para poder adquirir nuestros productos y acceder a
            todas las funciones de nuestra web
        </p>
        <form method="post"
            class="mb-0 mt-6 space-y-4 rounded-lg p-4 shadow-lg sm:p-6 lg:p-8">
            <div class="relative">
                {% csrf_token %}
                {{ form|crispy }}
            </div>
            <button type="submit"
                class="block w-full rounded-lg bg-indigo-600 px-5 py-3 text-sm font-medium text-white">
                Registrarse
            </button>
            <p class="text-center text-sm text-gray-500">
                Ya tienes una cuenta?
                <a class="underline" href="{% url 'login' %}">Inicia
                    sesión</a>
            </p>
        </form>
    </div>
</div>
{% endblock content %}